import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { randomBytes } from 'node:crypto';
import { tokenHash } from '@/lib/token-hash';

// vlayer-ignore security-sql-template-literal-* -- Supabase parameterizes fixed-column queries; interpolation only formats the one-time token response.
export async function GET() { const db=await createClient(); const {data:{user}}=await db.auth.getUser(); if(!user)return NextResponse.json({error:'Unauthorized'},{status:401}); const {data,error}=await db.from('projects').select('id,name,repo_url,created_at').order('created_at',{ascending:false}); return NextResponse.json(data??[],{status:error?500:200}); }
// vlayer-ignore security-sql-template-literal-* -- Supabase parameterizes fixed-column queries; interpolation only formats the one-time token response.
export async function POST(req:Request) { const db=await createClient(); const {data:{user}}=await db.auth.getUser(); if(!user)return NextResponse.json({error:'Unauthorized'},{status:401}); const body=await req.json().catch(()=>({})); if(typeof body.name!=='string'||!body.name.trim())return NextResponse.json({error:'name is required'},{status:400}); const {data:p,error}=await db.from('projects').insert({user_id:user.id,name:body.name.trim(),repo_url:typeof body.repository==='string'?body.repository:null}).select('id,name,repo_url').single(); if(error||!p)return NextResponse.json({error:'Unable to create project'},{status:500}); const token=`vlr_${randomBytes(24).toString('base64url')}`; const {error:te}=await db.from('project_tokens').insert({project_id:p.id,user_id:user.id,key_hash:tokenHash(token),key_prefix:token.slice(0,12),name:typeof body.tokenLabel==='string'?body.tokenLabel:'CI'}); if(te)return NextResponse.json({error:'Project created but token failed'},{status:500}); return NextResponse.json({...p,token},{status:201}); }
