import { readFileSync } from 'node:fs';
import { join } from 'node:path';

// Read the pre-generated sample report once at build time. The page is fully
// static — the report content never changes at runtime.
export const dynamic = 'force-static';

// A minimal top strip, injected into the standalone report HTML so visitors
// know what they are looking at and can get back to the agencies page. The
// report body itself is left untouched.
const BANNER = `<div style="position:sticky;top:0;z-index:50;background:#0066CC;color:#fff;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.4;padding:10px 20px;text-align:center;box-shadow:0 1px 3px rgba(0,0,0,0.15);">Sample report &mdash; generated by VLayer against a demo Next.js healthcare app. <a href="/sample-report.pdf" download style="color:#fff;text-decoration:underline;font-weight:600;">Download PDF</a> &middot; <a href="/agencies" style="color:#fff;text-decoration:underline;font-weight:600;">White-label this for your agency &rarr;</a></div>`;

function loadReport(): string {
  const html = readFileSync(
    join(process.cwd(), 'app', 'sample-report', 'sample-report.html'),
    'utf-8',
  );
  // Inject the banner immediately after <body> so it sits above the report.
  return html.replace(/<body[^>]*>/i, (match) => `${match}\n${BANNER}`);
}

export function GET(): Response {
  return new Response(loadReport(), {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
    },
  });
}
